language: ruby

rvm:
  - 2.3.0

branches:
  only:
    - master

notifications:
  email:
    on_success: change
    on_failure: always

before_install: "gem install bundler -v 1.11.2"
install: "bundle --jobs 4"
script: "bundle exec rspec"
